<?php

namespace App\Enums;

enum OrderLogActivityStatus: string
{
    case DRAFT_CREATED = 'draft_created';
    case DRAFT_CANCELLED = 'draft_cancelled';

    case PO_FILE_GENERATED = 'po_file_generated';

    case ORDER_CREATED = 'order_created';
    case ORDER_CANCELLED = 'order_cancelled';

    case DELETED = 'deleted';

    public function label(): string
    {
        return match ($this) {
            self::DRAFT_CREATED => '(Draft)',
            self::DRAFT_CANCELLED => '(Draft Cancel)',
            self::PO_FILE_GENERATED => '(PO File)',
            self::ORDER_CREATED => '(Success)',
            self::ORDER_CANCELLED => '(Cancel)',
            self::DELETED => '(Delete)',
        };
    }

    public function template(): string
    {
        return match ($this) {
            self::DRAFT_CREATED => 'Order PO %s: Draft successfully created by User ID %s.',
            self::DRAFT_CANCELLED => 'Order PO %s: Draft successfully cancelled by User ID %s.',
            self::PO_FILE_GENERATED => 'Order PO %s: File successfully generated by User ID %s.',
            self::ORDER_CREATED => 'Order PO %s: Successfully created by User ID %s.',
            self::ORDER_CANCELLED => 'Order PO %s: Order successfully cancelled by User ID %s.',
            self::DELETED => 'Order PO %s: Record successfully deleted by User ID %s.',
        };
    }
}
